// The lines of the sort test (sort.test.mjs): every request with the path step 2
// must give it. 81 are real — the 25 lines typed into Bonsai between 25 and 27
// Sep 2026, the 28 practice tasks and the 28 real requests of the test bench —
// and 20 are traps written to catch side effects of a rule.
//   prior: the line was typed after an earlier turn of the same conversation
//   path:  quit · chat · memory · follow-up · rename · fix · change · question · other · unsorted (the model sorts it)
//   ask:   null · 'fixed' (a set question) · 'model' (the model is asked whether it is clear) · 'where'
//   was:   where the line went before the 2026-09-27 rules (only where that changed)
export const LINES = [
  { set: 'yours', n: 1, prior: false, path: 'chat', ask: null, text: "hello" },
  { set: 'yours', n: 2, prior: true, path: 'quit', ask: null, text: "exit" },
  { set: 'yours', n: 3, prior: false, path: 'other', ask: null, text: "CREATE A TXT FILE AND NAME IT \"TEST\" . ADD A SHORT STORY INSIDE AND ADD IT TO MY DESKTOP WHEN YOU ARE DONE." },
  { set: 'yours', n: 4, prior: true, path: 'other', ask: null, text: "CREATE A TXT FILE AND NAME IT \"TEST\" . ADD A SHORT STORY INSIDE AND ADD IT TO MY DESKTOP WHEN YOU ARE DONE" },
  { set: 'yours', n: 5, prior: false, path: 'chat', ask: null, text: "hello" },
  { set: 'yours', n: 6, prior: true, path: 'question', ask: null, text: "tell me about multiplication, how does it work?" },
  { set: 'yours', n: 7, prior: true, path: 'quit', ask: null, text: "exit" },
  { set: 'yours', n: 8, prior: false, path: 'chat', ask: null, text: "hello , can you help me with something?" },
  { set: 'yours', n: 9, prior: true, path: 'follow-up', ask: null, was: { path: 'question', ask: 'model' }, text: " why" },
  { set: 'yours', n: 10, prior: true, path: 'chat', ask: null, was: { path: 'unsorted', ask: null }, text: "hello , ima need help with something" },
  { set: 'yours', n: 11, prior: true, path: 'other', ask: null, text: "I WANT YOU TO MAKE ME A FILE ON MY DESKTOP. MAKE A TXT FILE TITLED \"HELLO TEST 26 SEP\" AND WRITE A SHORT STOY ON A MONSTER IN A LAKE . REPORT BACK WHEN YOU ARE DONE" },
  { set: 'yours', n: 12, prior: false, path: 'chat', ask: null, text: "hello , can you help me with something ?" },
  { set: 'yours', n: 13, prior: true, path: 'other', ask: null, text: "can you create a txt file on my desktop and title it \"star\" and inside of it write a story about pirates at sea" },
  { set: 'yours', n: 14, prior: false, path: 'chat', ask: null, text: "hello" },
  { set: 'yours', n: 15, prior: true, path: 'chat', ask: null, was: { path: 'unsorted', ask: null }, text: "i want you to help me with something" },
  { set: 'yours', n: 16, prior: true, path: 'question', ask: null, text: "how good are you , on a scale from 1-10, at making self contained html files?" },
  { set: 'yours', n: 17, prior: true, path: 'other', ask: null, was: { path: 'change', ask: null }, text: "can you create a self contained html file and design a simple and modern finance dashbaord?" },
  { set: 'yours', n: 18, prior: false, path: 'other', ask: null, text: "create a self contained html file . i want it to be a note page . add it to my desktop when you are done" },
  { set: 'yours', n: 19, prior: false, path: 'other', ask: null, text: "Create one self-contained HTML file called notes.html that works when I double-click it, with all the CSS and   │\n│ JavaScript inside the file, nothing loaded from the internet, and <meta charset=\"utf-8\"> in the head. The page    │\n│ shows a \"+ New note\" button above a list of note cards. When I click the button, open a small modal in the middle │\n│  of the page and dim the page behind it. Inside the modal, show a title line, a text box for the note, and Cancel │\n│  and Save buttons. When I click Save, close the modal and add the note as a small card at the top of the list,    │\n│ showing the title, the first line of the note, and today's date. Cancel or the Escape key closes the modal        │\n│ without saving. Save the notes in the browser's local storage so they are still there when I reopen the file, and │\n│  follow my system's light or dark mode. download it to my desktop when you are done" },
  { set: 'yours', n: 20, prior: true, path: 'other', ask: null, text: "Create one self-contained HTML file called notes.html that works when I double-click it, with all the CSS and JavaScript inside the file, nothing loaded from the internet, and <meta charset=\"utf-8\"> in the head. The page shows a \"+ New note\" button above a list of note cards. When I click the button, open a small modal in the middle of the page and dim the page behind it. Inside the modal, show a title line, a text box for the note, and Cancel and Save buttons. When I click Save, close the modal and add the note as a small card at the top of the list, showing the title, the first line of the note, and today's date. Cancel or the Escape key closes the modal without saving. Save the notes in the browser's local storage so they are still there when I reopen the file, and follow my system's light or dark mode." },
  { set: 'yours', n: 21, prior: true, path: 'other', ask: null, text: "Create one self-contained HTML file called notes.html that works when I double-click it, with all the CSS and JavaScript inside the file, nothing loaded from the internet, and <meta charset=\"utf-8\"> in the head. The page shows a \"+ New note\" button above a list of note cards. When I click the button, open a small modal in the middle of the page and dim the page behind it. Inside the modal, show a title line, a text box for the note, and Cancel and Save buttons. When I click Save, close the modal and add the note as a small card at the top of the list, showing the title, the first line of the note, and today's date. Cancel or the Escape key closes the modal without saving. Save the notes in the browser's local storage so they are still there when I reopen the file, and follow my system's light or dark mode." },
  { set: 'yours', n: 22, prior: true, path: 'follow-up', ask: null, was: { path: 'change', ask: null }, text: "can you add it to my desktop?" },
  { set: 'yours', n: 23, prior: true, path: 'chat', ask: null, was: { path: 'unsorted', ask: null }, text: "its perfect , thank you" },
  { set: 'yours', n: 24, prior: true, path: 'memory', ask: null, text: "update memory" },
  { set: 'yours', n: 25, prior: false, path: 'other', ask: null, text: "analyze the file and wait for further instrcutions ~/Desktop/notes.html" },
  { set: 'tasks', n: 1, prior: false, path: 'change', ask: null, text: "add a --json flag to export.mjs that prints the rows as JSON, and add a test for it" },
  { set: 'tasks', n: 2, prior: false, path: 'fix', ask: null, text: "The tests in this project fail. Find the bug and fix it (fix the code, not the tests)." },
  { set: 'tasks', n: 3, prior: false, path: 'change', ask: null, text: "Add a titleCase(text) function to strings.mjs that capitalizes the first letter of every word and lowercases the rest, export it, and add a test for it." },
  { set: 'tasks', n: 4, prior: false, path: 'rename', ask: null, text: "Rename the function calcTotal to totalPrice everywhere in this project." },
  { set: 'tasks', n: 5, prior: false, path: 'question', ask: null, text: "Which port does this project's server listen on, and where is that set? Don't change any files." },
  { set: 'tasks', n: 6, prior: false, path: 'question', ask: null, text: "What is the default page size of paginate(), and where is it set? Don't change any files." },
  { set: 'tasks', n: 7, prior: false, path: 'question', ask: null, text: "Which function computes tax in this project, and what is its default rate? Don't change any files." },
  { set: 'tasks', n: 8, prior: false, path: 'rename', ask: null, text: "Rename the method getTotal to computeTotal everywhere in this project." },
  { set: 'tasks', n: 9, prior: false, path: 'rename', ask: null, text: "Rename the constant MAX_ITEMS to ITEM_LIMIT everywhere in this project." },
  { set: 'tasks', n: 10, prior: false, path: 'fix', ask: null, text: "The tests in this project fail. Find the bug and fix it (fix the code, not the tests)." },
  { set: 'tasks', n: 11, prior: false, path: 'fix', ask: null, text: "The tests in this project fail. Find the bug and fix it (fix the code, not the tests)." },
  { set: 'tasks', n: 12, prior: false, path: 'change', ask: null, text: "Add a currency option to formatMoney() in money.mjs, so formatMoney(1234.5, { currency: 'EUR' }) returns '€1,234.50' (keep '$' as the default), and add a test for it." },
  { set: 'tasks', n: 13, prior: false, path: 'change', ask: null, text: "Add a clamp(value, low, high) function to mathutil.py that limits value to the range low..high, and add a test for it." },
  { set: 'tasks', n: 14, prior: false, path: 'change', ask: null, text: "Add a perimeter(w, h) function to shapes.mjs that returns the perimeter of a w-by-h rectangle." },
  { set: 'tasks', n: 15, prior: false, path: 'fix', ask: null, text: "toFahrenheit() in convert.mjs gives wrong answers (100 °C should be 212 °F). Fix it." },
  { set: 'tasks', n: 16, prior: false, path: 'other', ask: null, text: "Create a text file called STORY.txt with a short story (at least five sentences) about a lighthouse keeper." },
  { set: 'tasks', n: 17, prior: false, path: 'other', ask: null, text: "Add a NOTES.md file with three bullet points explaining how the API in server.mjs works." },
  { set: 'tasks', n: 18, prior: false, path: 'other', ask: null, text: "CREATE A TXT FILE AND NAME IT \"TEST\" . ADD A SHORT STORY INSIDE AND ADD IT TO THIS FOLDER WHEN YOU ARE DONE" },
  { set: 'tasks', n: 19, prior: false, path: 'change', ask: null, text: "Add a symbol option (default '$') to the defaults in config.mjs, and use it in formatMoney in format.mjs and in the report header in report.mjs, so that buildReport(rows, { symbol: '€' }) starts with 'Total in €' and formats every amount with €. Add a test for it." },
  { set: 'tasks', n: 20, prior: false, path: 'change', ask: null, text: "applyDiscount in price.mjs should take a third argument, cap (default 50): a pct above the cap is limited to the cap. cartTotal in cart.mjs must pass a cap of 30 and invoiceLine in invoice.mjs a cap of 10. Add tests for the cap." },
  { set: 'tasks', n: 21, prior: false, path: 'fix', ask: null, text: "The tests in this project fail. Find the bug and fix it (fix the code, not the tests)." },
  { set: 'tasks', n: 22, prior: false, path: 'fix', ask: 'fixed', text: "fix the bug" },
  { set: 'tasks', n: 23, prior: false, path: 'unsorted', ask: 'model', text: "api" },
  { set: 'tasks', n: 24, prior: false, path: 'fix', ask: 'fixed', text: "fix the test" },
  { set: 'tasks', n: 25, prior: false, path: 'question', ask: null, text: "Where is the test command for a project decided, and what command does it return for a Python project? Don't change any files." },
  { set: 'tasks', n: 26, prior: false, path: 'change', ask: null, text: "Make List and Search skip a folder called tmp as well (the same way they skip node_modules), and add a test for it." },
  { set: 'tasks', n: 27, prior: false, path: 'change', ask: null, text: "formatMoney in money.mjs must put the minus sign before the currency symbol for negative amounts: formatMoney(-1234.5) is '-$1,234.50' and formatMoney(-0.5) is '-$0.50'. Positive amounts and zero stay as they are today. Add a test for negative amounts." },
  { set: 'tasks', n: 28, prior: false, path: 'change', ask: null, text: "Add a fee field to Trade in models.py (default 0.0) and include fee in to_dict in serialize.py; value must be qty * price minus the fee. Add a test for it." },
  { set: 'requests', n: 1, prior: false, path: 'chat', ask: null, text: "hello" },
  { set: 'requests', n: 2, prior: false, path: 'chat', ask: null, text: "thanks!" },
  { set: 'requests', n: 3, prior: false, path: 'question', ask: null, text: "What does the API in export.mjs do?" },
  { set: 'requests', n: 4, prior: false, path: 'question', ask: null, text: "Is there an API key in this project?" },
  { set: 'requests', n: 5, prior: false, path: 'question', ask: null, was: { path: 'question', ask: 'model' }, text: "explain the tests" },
  { set: 'requests', n: 6, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "run the tests" },
  { set: 'requests', n: 7, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "TEST" },
  { set: 'requests', n: 8, prior: false, path: 'unsorted', ask: 'model', text: "api" },
  { set: 'requests', n: 9, prior: false, path: 'other', ask: null, text: "add notes about the API to NOTES.md" },
  { set: 'requests', n: 10, prior: false, path: 'other', ask: null, text: "write a short poem about trading in poem.md" },
  { set: 'requests', n: 11, prior: false, path: 'other', ask: null, text: "CREATE A TXT FILE AND NAME IT \"TEST\" . ADD A SHORT STORY INSIDE" },
  { set: 'requests', n: 12, prior: false, path: 'other', ask: null, text: "update the README with how to run the tests" },
  { set: 'requests', n: 13, prior: false, path: 'other', ask: null, text: "create a new file called slug.mjs with a slugify(text) function" },
  { set: 'requests', n: 14, prior: false, path: 'change', ask: null, text: "add a --json flag to export.mjs that prints the rows as JSON" },
  { set: 'requests', n: 15, prior: false, path: 'fix', ask: 'fixed', text: "fix the test" },
  { set: 'requests', n: 16, prior: false, path: 'rename', ask: null, was: { path: 'rename', ask: 'model' }, text: "rename test to check" },
  { set: 'requests', n: 17, prior: false, path: 'other', ask: null, text: "rename export.mjs to exporter.mjs" },
  { set: 'requests', n: 18, prior: false, path: 'other', ask: null, text: "delete trades.json" },
  { set: 'requests', n: 19, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "run rm -rf ./logs to clean up" },
  { set: 'requests', n: 20, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "run sudo ls to check the permissions" },
  { set: 'requests', n: 21, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "kill the node server on port 3999" },
  { set: 'requests', n: 22, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "commit and push to github" },
  { set: 'requests', n: 23, prior: false, path: 'other', ask: null, was: { path: 'unsorted', ask: null }, text: "git reset --hard" },
  { set: 'requests', n: 24, prior: false, path: 'question', ask: null, text: `Here is a log, what went wrong?\n${'ERROR connection refused at 127.0.0.1:5432\n'.repeat(60)}` },
  { set: 'requests', n: 25, prior: false, path: 'chat', ask: null, text: "hello" },
  { set: 'requests', n: 26, prior: false, path: 'change', ask: null, text: "add a --json flag to export.mjs" },
  { set: 'requests', n: 27, prior: false, path: 'fix', ask: 'fixed', text: "fix the bug" },
  { set: 'requests', n: 28, prior: false, path: 'question', ask: null, text: "what does mathutil do?" },
  { set: 'traps', n: 1, prior: false, path: 'change', ask: null, text: "great, now add a --json flag to export.mjs" },
  { set: 'traps', n: 2, prior: false, path: 'rename', ask: null, text: "thanks, now rename calcTotal to totalPrice" },
  { set: 'traps', n: 3, prior: false, path: 'fix', ask: 'where', text: "perfect, fix the failing date test" },
  { set: 'traps', n: 4, prior: false, path: 'unsorted', ask: null, text: "i need help with the export function in export.mjs" },
  { set: 'traps', n: 5, prior: false, path: 'unsorted', ask: null, text: "exit the loop early in parse() when the row is empty" },
  { set: 'traps', n: 6, prior: false, path: 'unsorted', ask: null, text: "quit using var in export.mjs" },
  { set: 'traps', n: 7, prior: true, path: 'fix', ask: null, text: "fix this bug in export.mjs" },
  { set: 'traps', n: 8, prior: true, path: 'question', ask: null, text: "why does export.mjs crash on an empty file?" },
  { set: 'traps', n: 9, prior: true, path: 'question', ask: null, text: "tell me about multiplication, how does it work?" },
  { set: 'traps', n: 10, prior: true, path: 'rename', ask: null, text: "rename it to loadBars" },
  { set: 'traps', n: 11, prior: true, path: 'change', ask: null, text: "add a test for formatMoney and run it" },
  { set: 'traps', n: 12, prior: true, path: 'change', ask: null, text: "make this function faster: toCsv in export.mjs" },
  { set: 'traps', n: 13, prior: false, path: 'fix', ask: null, text: "run the tests and fix what fails" },
  { set: 'traps', n: 14, prior: false, path: 'unsorted', ask: null, text: "build a login page component in src/pages/Login.jsx" },
  { set: 'traps', n: 15, prior: false, path: 'other', ask: null, text: "create a new file called slug.mjs with a slugify(text) function" },
  { set: 'traps', n: 16, prior: false, path: 'change', ask: null, text: "add a settings page to the app" },
  { set: 'traps', n: 17, prior: false, path: 'change', ask: 'model', text: "make it faster" },
  { set: 'traps', n: 18, prior: false, path: 'unsorted', ask: null, text: "install lodash and use it in export.mjs to group the rows" },
  { set: 'traps', n: 19, prior: true, path: 'question', ask: null, text: "what does this project do?" },
  { set: 'traps', n: 20, prior: true, path: 'change', ask: null, text: "add a --json flag to export.mjs that prints the rows as JSON" },
];
